Dataframe viewer scrolling
EdwardBrodskiy/Personalized-Finance-Assistant pull request #3
Opened 2023-06-24 16:23 UTC by sheldonmlee

I have polished up the scrolling implementation

2023-06-24 22:29 UTC, sheldonmlee commented
Commit c37b74d5bea22d587a5c533271182c9c11fcda94 may need some reviewing to make sure it doesn't break stuff.

This commit was to address extra manual classification entries being created with the same ref, when going back and submitting previously submitted entries in 1083329e040c8787f605650daf665f96e03c57db.

2023-07-03 10:14 UTC, EdwardBrodskiy commented on classifier/rule_classifier.py
> +        for i, tag in enumerate(new_data['Tags'].values):
Is this a fillna operation? If so please use pandas method

2023-07-03 10:21 UTC, EdwardBrodskiy commented
Looking at what you did to process_incoming_input. Can't agree with the implementation. The original method was clean short and simple. It should not be touched. Modification should be moved to a separate method. This way you do not need to handle a bunch of edge cases. I would suggest i different implementation:

 - Each entered row has a edit and delete button which appear onHover
    - When a button is clicked this creates a popup with fields (would be good to reuse the ones from row entry if possible)
    - No index edge cases need to be handled as table index is implied by the button.
    - this then calls a new method in the rule classifier which can alter the internal data.

2023-07-17 13:21 UTC, EdwardBrodskiy requested changes

2023-07-17 13:21 UTC, EdwardBrodskiy commented on classifier/rule_classifier.py
> +        new_data = pd.DataFrame(data, columns=self.labeled_data.columns)
This seems like a pointless addition as you use astype in the next line anyway

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/ingest_process.py
> +        if self.reference_table.scroll(1):
this if condition is unclear please specify with a comment or rename the function

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/ingest_process.py
> +        if self.reference_table.scroll(-1):
same here

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/ingest_process.py
> +        if self.reference_table.scroll(1):
I am guessing this is handling the end of table case in which case you should consider re naming the method to "try_scroll_to" or "try_scroll"

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/row_entry.py
> +    def __init__(self, master, on_enter=None,  **kwargs):
make sure you refactor your files before we merge to master

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/row_entry.py
> +    def __init__(self, master, on_enter=None,  **kwargs):
*double space

2023-07-17 13:21 UTC, EdwardBrodskiy commented on web_app/ingest_page/row_entry.py
> +    def _draw_label_row(self, parent, row, grid_row):
I am guessing all of this additional code is for that grouped row view in which that is fine. But maybe consider extracting it as its own component.

2023-07-29 14:38 UTC, merged